# opacity rules
windowrule = opacity 1 override, match:float 0
windowrule = opacity 1 override, match:fullscreen 1

# smart gaps
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:workspace f[1]
windowrule = rounding 0, match:workspace f[1]

# screenshots
layerrule = no_anim 1, match:namespace hyprpicker
layerrule = no_anim 1, match:namespace selection

# pinned windows
windowrule = border_color rgb(585b70) rgb(585b70), match:pin 1
windowrule = opacity 1 override, match:pin 1
windowrule = opaque 1, match:pin 1

# floating windows
windowrule = float 1, match:title ^(Picture-in-Picture)$
windowrule = float 1, match:class ^(kitty)$
windowrule = float 1, match:class ^(imv)$
windowrule = float 1, match:class ^(vesktop)$
windowrule = float 1, match:class ^(spotify)$
windowrule = float 1, match:class ^(qBittorrent)$
windowrule = float 1, match:class ^(xdg-desktop-portal-gtk)$

# special workspace
windowrule = workspace special:s silent, match:class ^(vesktop)$
windowrule = workspace special:s silent, match:class ^(spotify)$
